on: [push, pull_request]
name: CI
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@7195340a122321bf547fda2ffc07eed6f6ae43f6 # v4.5.1

      - name: Install npm dependencies in js directory
        run: |
          cd js
          npm install
      
      - name: Run linting
        run: |
          cd js
          npm run lint
  
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@7195340a122321bf547fda2ffc07eed6f6ae43f6 # v4.5.1

      - name: Install npm dependencies in js directory
        run: |
          cd js
          npm install
            
      - name: Run formatting checks
        run: |
          cd js
          npm run format:check

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@7195340a122321bf547fda2ffc07eed6f6ae43f6 # v4.5.1

      - name: Install npm dependencies in js directory
        run: |
          cd js
          npm install

      - name: Run unit tests
        run: make unit-tests