[package]
edition = "2021"
name = "javy-plugin-kubewarden"
version = "0.1.1"

[lib]
crate-type = ["cdylib"]
name = "javy_plugin_kubewarden"

[dependencies]
javy-plugin-api = "4.0"
wit-bindgen = "0.46"
