- type: Exchange
  request: |
    !OciManifestAndConfig
    image: registry.testing.lan/nonexistent-image:1.0.0
  response:
    type: Error
    message: 'Failed to retrieve OCI manifest and config: image not found'