on: 
  - push
  - pull_request
  - workflow_call
  
name: CI
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@8fdccfcf973dfe199cb2f4b2a6809898aa721559 # v4.5.6

      - name: Install npm dependencies in js directory
        run: |
          cd js
          npm install
      
      - name: Run linting
        run: |
          cd js
          npm run lint
  
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@8fdccfcf973dfe199cb2f4b2a6809898aa721559 # v4.5.6

      - name: Install npm dependencies in js directory
        run: |
          cd js
          npm install
            
      - name: Run formatting checks
        run: |
          cd js
          npm run format:check

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@8fdccfcf973dfe199cb2f4b2a6809898aa721559 # v4.5.6

      - name: Install npm dependencies in js directory
        run: |
          cd js
          npm install

      - name: Run unit tests
        run: make unit-tests

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@8fdccfcf973dfe199cb2f4b2a6809898aa721559 # v4.5.6

      - name: Install npm dependencies in js directory
        run: |
          cd js
          npm install

      - name: Build TS code
        run: |
          cd js
          npm run build