on: 
  - push
  - pull_request
  - workflow_call
  
name: CI
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@5e22c63afd22d04a802a7a0463f66ffda6c3c71a # v4.5.7

      - name: Install npm dependencies in js directory
        run: |
          cd js
          npm install
      
      - name: Run linting
        run: |
          cd js
          npm run lint
  
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@5e22c63afd22d04a802a7a0463f66ffda6c3c71a # v4.5.7

      - name: Install npm dependencies in js directory
        run: |
          cd js
          npm install
            
      - name: Run formatting checks
        run: |
          cd js
          npm run format:check

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@5e22c63afd22d04a802a7a0463f66ffda6c3c71a # v4.5.7

      - name: Install npm dependencies in js directory
        run: |
          cd js
          npm install

      - name: Run unit tests
        run: make unit-tests

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@5e22c63afd22d04a802a7a0463f66ffda6c3c71a # v4.5.7

      - name: Override Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.82.0
          target: wasm32-wasip2
          cache: false
          override: true

      - name: Install wasm-tools
        shell: bash
        run: |
          #!/bin/bash
          set -e

          INSTALL_DIR=$HOME/.wasm-tools
          VERSION="1.220.0"

          mkdir -p $INSTALL_DIR
          curl -sL https://github.com/bytecodealliance/wasm-tools/releases/download/v${VERSION}/wasm-tools-${VERSION}-x86_64-linux.tar.gz -o $INSTALL_DIR/wasm-tools.tar.gz
          tar -xzf $INSTALL_DIR/wasm-tools.tar.gz -C $INSTALL_DIR
          mv $INSTALL_DIR/wasm-tools-${VERSION}-x86_64-linux/wasm-tools $INSTALL_DIR/wasm-tools
          rm -rf $INSTALL_DIR/wasm-tools.tar.gz $INSTALL_DIR/wasm-tools-${VERSION}-x86_64-linux

          chmod 755 $INSTALL_DIR/wasm-tools
          echo $INSTALL_DIR >> $GITHUB_PATH

          $INSTALL_DIR/wasm-tools --version

      - name: Install javy
        shell: bash
        run: |
          #!/bin/bash
          set -e

          INSTALL_DIR=$HOME/.javy
          VERSION="v7.0.0"

          mkdir -p $INSTALL_DIR
          curl -sL https://github.com/bytecodealliance/javy/releases/download/${VERSION}/javy-x86_64-linux-${VERSION}.gz -o $INSTALL_DIR/javy.gz
          gzip -d -c $INSTALL_DIR/javy.gz > $INSTALL_DIR/javy
          rm $INSTALL_DIR/javy.gz

          chmod 755 $INSTALL_DIR/javy
          echo $INSTALL_DIR >> $GITHUB_PATH

          $INSTALL_DIR/javy -V

      - name: Install npm dependencies in js directory
        run: |
          cd js
          npm install

      - name: Build TS code
        run: |
          cd js
          npm run build

      - name: Build plugin and policy
        run: |
          rustup add target wasm32-wasip2
          make all