on: 
  - push
  - pull_request
  - workflow_call
  
name: CI
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@17f4dbf90d74f26892f7cc18179d08c4d63914d9 # v4.5.4

      - name: Install npm dependencies in js directory
        run: |
          cd js
          npm install
      
      - name: Run linting
        run: |
          cd js
          npm run lint
  
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@17f4dbf90d74f26892f7cc18179d08c4d63914d9 # v4.5.4

      - name: Install npm dependencies in js directory
        run: |
          cd js
          npm install
            
      - name: Run formatting checks
        run: |
          cd js
          npm run format:check

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@17f4dbf90d74f26892f7cc18179d08c4d63914d9 # v4.5.4

      - name: Install npm dependencies in js directory
        run: |
          cd js
          npm install

      - name: Run unit tests
        run: make unit-tests

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@17f4dbf90d74f26892f7cc18179d08c4d63914d9 # v4.5.4

      - name: Install npm dependencies in js directory
        run: |
          cd js
          npm install

      - name: Build TS code
        run: |
          cd js
          npm run build