on: 
  - push
  - pull_request
  - workflow_call
  
name: Continuous integration
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.82.0
          target: wasm32-wasip2
          cache: false
      
      - name: Install kwctl
        run: |
          curl -L https://github.com/kubewarden/kwctl/releases/latest/download/kwctl-linux-x86_64.tar.gz | tar xvz
          sudo mv kwctl /usr/local/bin/
      - name: Install wasm-tools
        shell: bash
        run: |
          #!/bin/bash
          set -e

          INSTALL_DIR=$HOME/.wasm-tools
          VERSION="1.220.0"

          mkdir -p $INSTALL_DIR
          curl -sL https://github.com/bytecodealliance/wasm-tools/releases/download/v${VERSION}/wasm-tools-${VERSION}-x86_64-linux.tar.gz -o $INSTALL_DIR/wasm-tools.tar.gz
          tar -xzf $INSTALL_DIR/wasm-tools.tar.gz -C $INSTALL_DIR
          mv $INSTALL_DIR/wasm-tools-${VERSION}-x86_64-linux/wasm-tools $INSTALL_DIR/wasm-tools
          rm -rf $INSTALL_DIR/wasm-tools.tar.gz $INSTALL_DIR/wasm-tools-${VERSION}-x86_64-linux

          chmod 755 $INSTALL_DIR/wasm-tools
          echo $INSTALL_DIR >> $GITHUB_PATH

          $INSTALL_DIR/wasm-tools --version
      - name: Install javy
        shell: bash
        run: |
          #!/bin/bash
          set -e

          INSTALL_DIR=$HOME/.javy
          VERSION="v7.0.0"

          mkdir -p $INSTALL_DIR
          curl -sL https://github.com/bytecodealliance/javy/releases/download/${VERSION}/javy-x86_64-linux-${VERSION}.gz -o $INSTALL_DIR/javy.gz
          gzip -d -c $INSTALL_DIR/javy.gz > $INSTALL_DIR/javy
          rm $INSTALL_DIR/javy.gz

          chmod 755 $INSTALL_DIR/javy
          echo $INSTALL_DIR >> $GITHUB_PATH

          $INSTALL_DIR/javy -V

      - name: Install npm dependencies in js directory
        run: |
          cd js
          npm install

      - name: Run e2e tests
        run: make e2e-tests
