on:
  - push
  - pull_request
  - workflow_call

name: Continuous integration
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@605a03917fbc6b4b523145a1a78cf72a680f5f36 # v4.5.12
      # TODO: remove once kwctl 1.30.0 is released
      - name: Install kwctl
        uses: kubewarden/github-actions/kwctl-installer@605a03917fbc6b4b523145a1a78cf72a680f5f36 # v4.5.12
        with:
          KWCTL_VERSION: v1.30.0
      - name: Install javy
        shell: bash
        run: |
          #!/bin/bash
          set -e

          INSTALL_DIR=$HOME/.javy
          VERSION="v7.0.1"

          mkdir -p $INSTALL_DIR
          curl -sL https://github.com/bytecodealliance/javy/releases/download/${VERSION}/javy-x86_64-linux-${VERSION}.gz -o $INSTALL_DIR/javy.gz
          gzip -d -c $INSTALL_DIR/javy.gz > $INSTALL_DIR/javy
          rm $INSTALL_DIR/javy.gz

          chmod 755 $INSTALL_DIR/javy
          echo $INSTALL_DIR >> $GITHUB_PATH

          $INSTALL_DIR/javy -V

      - name: Install npm dependencies in js directory
        run: |
          cd js
          npm install

      - name: Run e2e tests
        run: make e2e-tests
