on: 
  - push
  - pull_request
  - workflow_call
  
name: Continuous integration
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@5e22c63afd22d04a802a7a0463f66ffda6c3c71a # v4.5.7
      - name: Setup Rust toolchain
        run: |
          rustup toolchain install stable
          rustup default stable
          rustup target add wasm32-wasip2
      - name: Install wasm-tools
        run: cargo install wasm-tools
      - name: Install javy
        shell: bash
        run: |
          #!/bin/bash
          set -e

          INSTALL_DIR=$HOME/.javy
          VERSION="v7.0.0"

          mkdir -p $INSTALL_DIR
          curl -sL https://github.com/bytecodealliance/javy/releases/download/${VERSION}/javy-x86_64-linux-${VERSION}.gz -o $INSTALL_DIR/javy.gz
          gzip -d -c $INSTALL_DIR/javy.gz > $INSTALL_DIR/javy
          rm $INSTALL_DIR/javy.gz

          chmod 755 $INSTALL_DIR/javy
          echo $INSTALL_DIR >> $GITHUB_PATH

          $INSTALL_DIR/javy -V

      - name: Install npm dependencies in js directory
        run: |
          cd js
          npm install

      - name: Run e2e tests
        run: make e2e-tests
