on:
  push:
    paths:
      - 'javy-plugin-kubewarden/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'javy-plugin-kubewarden/**'
      - '.github/workflows/**'
  workflow_call:

name: Javy plugin
jobs:
  rust-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: rust linters
        run: |
          cd javy-plugin-kubewarden
          cargo fmt --all -- --check
          cargo clippy -- -D warnings

