on:
  push:
    paths:
      - 'javy-plugin-kubewarden/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'javy-plugin-kubewarden/**'
      - '.github/workflows/**'

name: Javy plugin
jobs:
  rust-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: false
      - name: rust linters
        run: |
          cd javy-plugin-kubewarden
          cargo fmt --all -- --check
          cargo clippy -- -D warnings

