on:
  push:
    paths:
      - 'javy-plugin-kubewarden/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'javy-plugin-kubewarden/**'
      - '.github/workflows/**'

name: Javy plugin
jobs:
  rust-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install wasm32-wasip2 target
        run: |
          rustup target add wasm32-wasip2 --toolchain stable
          rustup target list --installed
          rustc --print target-list | grep wasm32-wasip2
      - name: rust linters
        run: |
          cd javy-plugin-kubewarden
          cargo fmt --all -- --check
          cargo clippy --target=wasm32-wasip2 -- -D warnings

