on:
  push:
    paths:
      - 'javy-plugin-kubewarden/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'javy-plugin-kubewarden/**'
      - '.github/workflows/**'

name: Javy plugin
jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: linters
        run: |
          cd javy-plugin-kubewarden
          cargo fmt --all -- --check
          cargo clippy -- -D warnings

